export const SETTINGS_KEY = 'SETTINGS'

export const VAULT_KEY = 'VAULT'

export const DEFAULT_AUTOLOCK_TIME_KEY = 'DEFAULT_AUTOLOCK_TIME'
export const AUTOLOCK_DEADLINE_KEY = 'AUTOLOCK_DEADLINE'

export const PASSWORD_CHECKER_KEY = 'PASSWORD_CHECKER'
