export const SETTINGS_KEY = 'SETTINGS'

export const WALLETS_KEY = 'WALLETS'

export const DEFAULT_AUTOLOCK_TIME_KEY = 'DEFAULT_AUTOLOCK_TIME'
export const AUTOLOCK_DEADLINE_KEY = 'AUTOLOCK_DEADLINE'


export const PASSWORD_CHECKER_KEY = 'PASSWORD_CHECKER'

export const ENCRYPTION_SALT_KEY = 'ENCRYPTION_SALT'
export const ENCRYPTION_IV_KEY = 'ENCRYPTION_IV'